# Generated by Django 6.0.3 on 2026-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_seed_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='ticket_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ticket size in £m', max_digits=10, null=True),
        ),
    ]
