# Generated by Django 5.0.2 on 2026-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='type',
            field=models.CharField(blank=True, choices=[('asset_manager', 'Asset manager'), ('bank', 'Bank'), ('endowment_charity', 'Endowment/charity'), ('fund_manager', 'Fund manager'), ('fund_of_funds', 'Fund of funds'), ('gatekeeper_consultant', 'Gatekeeper/consultant'), ('hnw_uhnw', 'HNW/UHNW'), ('insurance_company', 'Insurance company'), ('investment_company_trust', 'Investment company/trust'), ('pension_fund_company', 'Pension fund/company'), ('lgps', 'LGPS'), ('lgps_pool', 'LGPS pool'), ('single_family_office', 'Single family office'), ('swf_government', 'SWF/government'), ('wealth_manager_pb_mfo', 'Wealth manager/PB/MFO')], default='', max_length=30),
        ),
    ]
