# Generated by Django 5.0.2 on 2026-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_investor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='meeting',
            field=models.BooleanField(default=False),
        ),
    ]
