# Generated by Django 5.0.2 on 2026-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_investor_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
