# Generated by Django 5.0.2 on 2026-03-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_add_investor_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='prefequity_owner',
            field=models.CharField(blank=True, choices=[('TD', 'TD'), ('NP', 'NP'), ('JCP', 'JCP'), ('TB', 'TB'), ('PW', 'PW')], default='', max_length=10),
        ),
    ]
