# Generated by Django 5.0.2 on 2026-03-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_add_prefequity_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('participants', models.JSONField(blank=True, default=list, help_text='Prefequity participants (TD, NP, JCP, TB, PW)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_logs', to='crm.investor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
