# Generated by Django 5.0.2 on 2026-03-15 16:52

from django.db import migrations, models


def migrate_status_forward(apps, schema_editor):
    Investor = apps.get_model('crm', 'Investor')
    Investor.objects.filter(status='potential_sma').update(status='target_sma')


def migrate_status_backward(apps, schema_editor):
    Investor = apps.get_model('crm', 'Investor')
    Investor.objects.filter(status='target_sma').update(status='potential_sma')
    Investor.objects.filter(status='target_feeder_fund').update(status='target_fund_iii')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_meeting_log'),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('target_sma', 'Target for SMA'), ('target_feeder_fund', 'Target for Feeder Fund'), ('target_fund_iii', 'Target for Fund III'), ('confirmed', 'Confirmed'), ('other', 'Other')], default='target_fund_iii', max_length=20),
        ),
    ]
