# Generated by Django 5.0.2 on 2026-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_update_investor_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='investor_participants',
            field=models.JSONField(blank=True, default=list, help_text='Investor participants: principal, contact:pk'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='participants',
            field=models.JSONField(blank=True, default=list, help_text='Prefequity participants (TD, NP, JCP, TB, PW)'),
        ),
        migrations.AddField(
            model_name='meetinglog',
            name='investor_participants',
            field=models.JSONField(blank=True, default=list, help_text='Investor participants: principal, contact:pk'),
        ),
    ]
