# Generated by Django 5.0.2 on 2026-03-17 20:13

from django.db import migrations, models


def migrate_status_to_statuses(apps, schema_editor):
    Investor = apps.get_model('crm', 'Investor')
    for investor in Investor.objects.all():
        if hasattr(investor, 'status') and investor.status:
            investor.statuses = [investor.status]
        else:
            investor.statuses = ['target_fund_iii']
        investor.save()


def migrate_statuses_to_status(apps, schema_editor):
    Investor = apps.get_model('crm', 'Investor')
    for investor in Investor.objects.all():
        investor.status = investor.statuses[0] if investor.statuses else 'target_fund_iii'
        investor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_meeting_call_participant_checkboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='statuses',
            field=models.JSONField(blank=True, default=list, help_text='List of status values (target_sma, target_feeder_fund, etc.)'),
        ),
        migrations.RunPython(migrate_status_to_statuses, migrate_statuses_to_status),
        migrations.RemoveField(
            model_name='investor',
            name='status',
        ),
    ]
